channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow==2.22.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.3.1
  - segmentation-models-pytorch==0.3.3
  - torch==2.1.2
  - transformers==4.40.2
name: mlflow-env
